
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://WS/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConversionEuToDh")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConversionEuToDh", targetNamespace = "http://WS/", className = "proxy.ConversionEuToDh")
    @ResponseWrapper(localName = "ConversionEuToDhResponse", targetNamespace = "http://WS/", className = "proxy.ConversionEuToDhResponse")
    @Action(input = "http://WS/BanqueService/ConversionEuToDhRequest", output = "http://WS/BanqueService/ConversionEuToDhResponse")
    public double conversionEuToDh(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param arg0
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://WS/", className = "proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://WS/", className = "proxy.GetCompteResponse")
    @Action(input = "http://WS/BanqueService/getCompteRequest", output = "http://WS/BanqueService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listesCompte", targetNamespace = "http://WS/", className = "proxy.ListesCompte")
    @ResponseWrapper(localName = "listesCompteResponse", targetNamespace = "http://WS/", className = "proxy.ListesCompteResponse")
    @Action(input = "http://WS/BanqueService/listesCompteRequest", output = "http://WS/BanqueService/listesCompteResponse")
    public List<Compte> listesCompte();

}
